update gh actions to use ubuntu 22.04 instead of latest due to issues with 24.04

diff --git a/.github/workflows/test-pr.yaml b/.github/workflows/test-pr.yaml
--- a/.github/workflows/test-pr.yaml
+++ b/.github/workflows/test-pr.yaml
@@ -5,7 +5,7 @@ on:
             - master
 jobs:
     build:
-        runs-on: ubuntu-latest
+        runs-on: ubuntu-22.04
         steps:
             - uses: actions/checkout@v3
             - uses: ./.github/workflows/setup
@@ -44,7 +44,7 @@ jobs:
                     # Implementation is too outdated to test in GitHub Actions
                     # - elm,schema-elm
 
-                    # Language is too niche / obscure to test easily on ubuntu-latest
+                    # Language is too niche / obscure to test easily on ubuntu-22.04
                     # - pike,schema-pike
 
                     # Not yet started
@@ -55,15 +55,15 @@ jobs:
                     # Never tested?
                     # - crystal
 
-                runs-on: [ubuntu-latest]
+                runs-on: [ubuntu-22.04]
 
                 include:
                     # Rust is very slow, so we use a larger runner
                     - fixture: rust,schema-rust
-                      runs-on: ubuntu-latest-8-cores
+                      runs-on: ubuntu-22.04-8-cores
                     # Kotlin is also slow
                     - fixture: kotlin,schema-kotlin,kotlin-jackson,schema-kotlin-jackson
-                      runs-on: ubuntu-latest-8-cores
+                      runs-on: ubuntu-22.04-8-cores
 
                     - fixture: objective-c
                       runs-on: macos-11
@@ -189,8 +189,8 @@ jobs:
     test-complete:
         if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
         needs: test
-        runs-on: ubuntu-latest
+        runs-on: ubuntu-22.04
         steps:
-          - run: |
-              echo "Some workflows have failed!"
-              exit 1
+            - run: |
+                  echo "Some workflows have failed!"
+                  exit 1
